title: IT2070 - Introduction to Data Science and Analytics
description: Fall 2023 Course Site
theme: just-the-docs

url: https://https://ktamerl4.github.io/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
